### ISSUE TITLE
Add capability to simulate across a range of rate parameter values

### ISSUE THREAD

**Issue by julianheavyside** [julianheavyside/diversification#13]
@mwpennell should I use a range of all possible combinations, or can I hold q10 constant while only adjusting q01?

**Comment by mwpennell** [comment]
we should vary both as it is not just the ratio that matters but the absolute values (or at least absolute, relative to tree depth). the absolute rates will determine how often we see character transitions. the ratio will determine how imbalanced these transitions are.

**Comment by julianheavyside** [comment]
That makes sense

**Comment by julianheavyside** [comment]
https://github.com/julianheavyside/diversification/blob/master/analysis.R#L73-L87

- [ ] We now have a range of different q01 and q10, and same q01 and q10, from 0.1 to 1.0
I made the increment across the range of values smaller, to keep the full list of pars relatively small. 

- [ ] Should I go back to the previous increment of .02?

- [ ] Should I go above a value of 1? Look up real values in literature

**Comment by mwpennell** [comment]
honestly can't give you a good answer here off the top of my head. but a good general strategy for these things is to first do a quick pilot study with a broad range of parameters at large intervals between them. identify the regions of parameter space that seem to matter and sample more densely in those regions for the real study.

looking of values from the literature is not really informative as it depends on the depth of your tree and possibly the branching structure.
