### ISSUE TITLE
Adjust y axis for each level of tree size (not ideal, but easier to visualize the effect of bias)

### ISSUE THREAD

**Issue by julianheavyside** [julianheavyside/diversification#20]
Larger trees aren't influence as strongly by biased data, so the y axis for all plots is dictated by error in small trees.

**Comment by julianheavyside** [comment]
use grid.arrange() to control y axes of separate plots

**Comment by mwpennell** [comment]
ggplot is great but its ease of use depends on limiting what is legal within its universe
