### ISSUE TITLE
Character states should not be simulated for each subsampled tree (keep old ones)

### ISSUE THREAD

**Issue by julianheavyside** [julianheavyside/diversification#4]
Don't simulate new character states for the pruned tree; use the old ones of course!

https://github.com/julianheavyside/diversification/blob/master/supporting-functions.R#L13

**Comment by julianheavyside** [comment]
@mwpennell Also, new_d is made using only the tip.labels from the new_t. Should it also have states for the node.labels?

**Comment by julianheavyside** [comment]
Now that I think about it, we only need the states for the tips. We are calculating the probability of obtaining the observed tip states, given a parameter value. We don't need knowledge of the ancestral node states.

**Comment by julianheavyside** [comment]
Fixed, here:
https://github.com/julianheavyside/diversification/blob/master/supporting-functions.R#L13

**Comment by mwpennell** [comment]
Yeah, you're correct. The node states are not used in the likelihood calculation. They are retained in the simulation so that people can look at other things (e.g., how many times the state switched, etc.)
